
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.slnx'
  buildConfiguration: 'Release'

steps:

# Install SDK
- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: sdk
    version: '10.0.x'

# Restore
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(solution)'

# Build
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: >
      --configuration $(buildConfiguration)
      --no-restore

# Test using Microsoft Testing Platform
# Test using Microsoft Testing Platform
- script: |
    echo "Running tests with Microsoft Testing Platform"

    dotnet test 
  displayName: Run Tests


# Publish test results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
    failTaskOnFailedTests: true

# Publish coverage
- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)/coverage.xml'
    
