global using Common.SharedKernel.Results;
global using Common.SharedKernel.Web;
global using FluentValidation;
global using MediatR;
global using Inventory.Api.Contracts;
global using Inventory.Api.Domain;
global using Inventory.Api.Infrastructure;
global using Inventory.Api.Infrastructure.Persistence;
global using Inventory.Api.Infrastructure.Outbox;
