services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: ..
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ..
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: ..
      dockerfile: src/Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: ..
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: ..
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: ..
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: ..
      dockerfile: src/ApiGateways/Shopping.Aggregator/Dockerfile


volumes:
  mongo_data:
    name: aspnetrun_mongo_data
  portainer_data:
    name: aspnetrun_portainer_data
  postgres_data:
    name: aspnetrun_postgres_data
  pgadmin_data:
    name: aspnetrun_pgadmin_data

